# Generated by Django 3.0.6 on 2020-10-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='currentPassengerCount',
            field=models.IntegerField(null=True),
        ),
    ]
